BTL_Nhom13/BTL_Nhom13/Areas/Admin/Controllers/AdminTaiKhoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTL_Nhom13.Models;
using PagedList;

namespace BTL_Nhom13.Areas.Admin.Controllers
{
    public class AdminTaiKhoansController : Controller
    {
        private TinhDauDB db = new TinhDauDB();

        public ActionResult Account(int? page)
        {
            // select only admin account
            var taiKhoans = db.TaiKhoans.Where(t => t.Quyen == 1).Select(t => t);
            taiKhoans = taiKhoans.OrderBy(t => t.TenTaiKhoan);
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(taiKhoans.ToPagedList(pageNumber, pageSize));
        }
        // GET: Admin/AdminTaiKhoans/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminTaiKhoans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TenTaiKhoan,MatKhau," +
            "Quyen,TinhTrang,TenKhachHang,Email,SoDienThoai,DiaChi")] TaiKhoan taiKhoan)
        {
            taiKhoan.Quyen = 1;
            try
            {
                if (ModelState.IsValid)
                {
                    db.TaiKhoans.Add(taiKhoan);
                    db.SaveChanges();
                }
                return RedirectToAction("Account");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu! " + ex.Message;
                return View(taiKhoan);
            }
        }

        // GET: Admin/AdminTaiKhoans/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: Admin/AdminTaiKhoans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TenTaiKhoan,MatKhau,Quyen,TinhTrang,TenKhachHang,Email,SoDienThoai,DiaChi")] TaiKhoan taiKhoan)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(taiKhoan).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Account");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu! " + ex.Message;
                return View(taiKhoan);
            }
        }

        // GET: Admin/AdminTaiKhoans/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: Admin/AdminTaiKhoans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);

            db.TaiKhoans.Remove(taiKhoan);
            db.SaveChanges();
            return RedirectToAction("Account");

        }
        public bool toggleStatus(string id)
        {
            var user = db.TaiKhoans.Find(id);
            user.TinhTrang = !user.TinhTrang;
            db.SaveChanges();
            return user.TinhTrang;
        }

        [HttpPost]
        public JsonResult ChangeStatus(string id)
        {
            var result = toggleStatus(id);
            return Json(new
            {
                status = result
            });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BTL_Nhom13/BTL_Nhom13/Areas/Admin/Views/AdminTaiKhoans/Account.cshtml
@model PagedList.IPagedList<BTL_Nhom13.Models.TaiKhoan>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Account";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    Tài khoản
}
<link href="~/Content/PagedList.css" rel="stylesheet" />
<style>
    .normal-text {
        text-transform: none;
    }

    .pagination {
        margin: 0px 0px;
    }
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <a href="@Url.Action("Create", "AdminTaiKhoans")" class="btn btn-sm btn-primary normal-text" role="button">Thêm mới</a>
        </div>
        <div class="col-sm-6" style="text-align:right">
            @Html.PagedListPager(Model, page => Url.Action("Account", new { page }))
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title">Danh sách tài khoản</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="text-primary">
                            <th>Tên tài khoản</th>
                            <th>Mật khẩu</th>
                            <th>Tình trạng</th>
                            <th>Hành động</th>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.TenTaiKhoan)</td>
                                        <td>@item.MatKhau</td>
                                        <td>
                                            @if (item.TinhTrang == true)
                                            {
                                                if (!item.TenTaiKhoan.Equals(Session["TenTaiKhoan"]))
                                                {
                                                    <div class="togglebutton">
                                                        <label>
                                                            <input type="checkbox" checked="checked" class="btn-active" data-id="@item.TenTaiKhoan">
                                                            <span class="toggle"></span>
                                                        </label>
                                                    </div>
                                                }
                                                else
                                                {
                                                    <div class="togglebutton">
                                                        <label>
                                                            <input type="checkbox" checked="checked" class="btn-active" data-id="@item.TenTaiKhoan" disabled="disabled">
                                                            <span class="toggle"></span>
                                                        </label>
                                                    </div>
                                                }
                                            }
                                            else
                                            {
                                                if (!item.TenTaiKhoan.Equals(Session["TenTaiKhoan"]))
                                                {
                                                    <div class="togglebutton">
                                                        <label>
                                                            <input type="checkbox" class="btn-active" data-id="@item.TenTaiKhoan">
                                                            <span class="toggle"></span>
                                                        </label>
                                                    </div>
                                                }
                                                else
                                                {
                                                    <div class="togglebutton">
                                                        <label>
                                                            <input type="checkbox" class="btn-active" data-id="@item.TenTaiKhoan" disabled="disabled">
                                                            <span class="toggle"></span>
                                                        </label>
                                                    </div>
                                                }
                                            }
                                        </td>
                                        <td>
                                            @if (!item.TenTaiKhoan.Equals(Session["TenTaiKhoan"]))
                                            {
                                                @Html.ActionLink("Xóa", "Delete", new { id = item.TenTaiKhoan.Trim() }, new { @class = "btn btn-sm btn-primary normal-text" })
                                                @Html.ActionLink("Sửa", "Edit", new { id = item.TenTaiKhoan.Trim() }, new { @class = "btn btn-sm btn-primary normal-text" })
                                            }
                                            else
                                            {
                                                @Html.ActionLink("Sửa", "Edit", new { id = item.TenTaiKhoan.Trim() }, new { @class = "btn btn-sm btn-primary normal-text" })
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="text-align: right">
        @Html.PagedListPager(Model, page => Url.Action("Account", new { page }))
    </div>
</div>
<script src="~/wwwroot/js/jquery.min.js"></script>
<script src="~/wwwroot/js/popper.js"></script>
<script src="~/wwwroot/js/bootstrap.min.js"></script>
<script src="~/wwwroot/js/main.js"></script>
@section Scripts {
    <script src="~/Areas/Admin/Assets/js/controller/tkquantri_status.js"></script>
}

BTL_Nhom13/BTL_Nhom13/Areas/Admin/Views/AdminTaiKhoans/Create.cshtml
@model BTL_Nhom13.Models.TaiKhoan

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    Thêm tài khoản mới
}
<style>
    .form-horizontal {
        padding-left: 7rem;
    }

    .col-md-10 {
        padding-left: 7rem;
    }

    .control-label, .bmd-form-group label {
        color: black;
    }
</style>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TenTaiKhoan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenTaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenTaiKhoan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TinhTrang, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.TinhTrang)
                @Html.ValidationMessageFor(model => model.TinhTrang, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    @Html.HiddenFor(model => model.TenKhachHang, new { @Value = "Người quản trị" })
    @Html.HiddenFor(model => model.Email, new { @Value = "quantrivien@gmail.com" })
    @Html.HiddenFor(model => model.SoDienThoai, new { @Value = "0378951234" })
    @Html.HiddenFor(model => model.DiaChi, new { @Value = "Hà Nội" })
    
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Thêm" class="btn btn-sm btn-primary normal-text" />
            @Html.ActionLink("Quay lại", "Account", null, new { @class = "btn btn-sm btn-primary normal-text" })
        </div>
    </div>
</div>
}

@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BTL_Nhom13/BTL_Nhom13/Areas/Admin/Views/AdminTaiKhoans/Delete.cshtml
@model BTL_Nhom13.Models.TaiKhoan

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    Xóa tài khoản
}
<style>
    .dl-horizontal {
        padding-left: 10rem;
    }

    dl dd {
        padding-left: 8rem;
    }
</style>
<h3>Bạn có chắc muốn xóa tài khoản này?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenTaiKhoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenTaiKhoan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quyen)
        </dt>

        <dd>
            Quản trị
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TinhTrang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TinhTrang)
        </dd>

        <dt>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <input type="submit" value="Xóa" class="btn btn-sm btn-primary normal-text" />
                @Html.ActionLink("Quay lại", "Account", null, new { @class = "btn btn-sm btn-primary normal-text" })
            }
        </dt>
    </dl>
</div>

BTL_Nhom13/BTL_Nhom13/Areas/Admin/Views/AdminTaiKhoans/Edit.cshtml
@model BTL_Nhom13.Models.TaiKhoan

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@section Title{
    Sửa thông tin tài khoản
}
<style>
    .form-horizontal {
        padding-left: 7rem;
    }

    .col-md-10 {
        padding-left: 8rem;
    }

    .control-label, .bmd-form-group label {
        color: black;
    }
</style>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TenTaiKhoan)

    <div class="form-group">
        @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control", @Value = Model.MatKhau } })
            @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.Quyen)

    @if (!Model.TenTaiKhoan.Equals(Session["TenTaiKhoan"]))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.TinhTrang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TinhTrang)
                    @Html.ValidationMessageFor(model => model.TinhTrang, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    } else
                {
                    @Html.HiddenFor(model => model.TinhTrang)
                }

    @Html.HiddenFor(model => model.TenKhachHang)
    @Html.HiddenFor(model => model.Email)
    @Html.HiddenFor(model => model.SoDienThoai)
    @Html.HiddenFor(model => model.DiaChi)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-sm btn-primary normal-text" />
            @Html.ActionLink("Quay lại", "Account", null, new { @class = "btn btn-sm btn-primary normal-text" })
        </div>
    </div>
</div>
}
@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}